import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import styles from "../../styles/Home.module.css";
import Head from "next/head";
import Link from "next/link";
import axios from "axios";
const PokeDetailPage = ()=>{
  const router = useRouter();
  const query = router.query;
  const id = query.id;
	const POKEMON_DETAIL_URL = `https://pokeapi.co/api/v2/pokemon/${id}/`;
  const [pokemonDetail, setPokemonDetail] = useState(null);
	
	useEffect(()=>{
    if(router.isReady){
			axios.get(POKEMON_DETAIL_URL)
			.then((res)=>{
				setPokemonDetail(res.data);
			}).catch((err)=>{
				console.log(err);
			});
		}
  }, [query,router]);

	return(
		pokemonDetail? 
		<div className={styles.container}>
      <Head>
        <title>Poke_detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="font-3xl">
          名前: {pokemonDetail.name}
        </div>
				<div>
					<ul>
						<li>重さ: {pokemonDetail.weight} kg</li>
						<li>大きさ: {pokemonDetail.height} cm</li>
						{pokemonDetail.types.map((type,index)=>{
							return(
								<li>
									タイプ{index}: {type.type.name}
								</li>
							);
						})}
					</ul>
				</div>

      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          
        </a>
      </footer>
    </div>:<div></div>
	);
}

export default PokeDetailPage;