import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "../../styles/Home.module.css";
import axios from "axios";

export default function Home() {
  const [pokemonList, setPokemonList] = useState([]);
  const POKEMON_LIST_URL = "https://pokeapi.co/api/v2/pokemon?limit=100000&offset=0";
  
  useEffect(()=>{
    axios.get(POKEMON_LIST_URL)
    .then((res)=>{
        setPokemonList(res.data.results);
    }).catch((err)=>{
        console.log(err);
    });
  },[]);

	const getIdFromURL = (url)=>{
		return url.split("/").slice(-2)[0];
	}

  return (
    <div className={styles.container}>
      <Head>
        <title>Poke_dict</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          {pokemonList.map((pokemon,index)=>{
						const pokemonId = getIdFromURL(pokemon.url);
						return(
							<div>
								<div className="underline text-blue-500 text-xl ">
									<Link
										href={`/poke/${pokemonId}`}
									>
										{pokemon.name}
									</Link>
								</div>
							</div>
							
						);
					})}
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
